export default {
  BLACK: "#000",
  WHITE: "#FFF",
  GRAY: "#808080",
  DEFAULT_BLUE: "#4267B2",
  DEFAULT_LIGHT: "#9DA1A5",
  GRAY_LIGHT: "#d6dbdb",
  INPUT_BACKGROUND: "#262626",
  CUSTOM_LIGHT: "#5a5b5c",
TAB_ICON_COLOR : "black",
TAB_ICON_COLOR_ACTIVE : "black",
};
